import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { Fragment, useEffect, useState } from "react";
import Script from "next/script";
import { api } from "~/utils/api";
import VehicleSelection from "~/components/vehicleSelection";
import GeoLocation from "~/components/geoLocation";
import { vehicle } from "@prisma/client";
import { atom, useAtomValue } from "jotai";
import Map from "~/components/map";

//Global atoms for selected vehicle and vehicle range
export const vehicleRangeAtom = atom<number>(0);
export const selectedVehicleAtom = atom<vehicle | null>(null);

//Derived atom for distance based on selected vehicle, vehicle range, and vehicle mpg
export const distanceAtom = atom((get) =>
  Math.floor(
    (get(selectedVehicleAtom)?.vehicle_mpg ?? 0) *
      (get(selectedVehicleAtom)?.vehicle_gallons ?? 0) *
      get(vehicleRangeAtom) || 0
  )
);

//Home page component
const Home: NextPage = () => {
  const vehicle = useAtomValue(selectedVehicleAtom);
  const range = useAtomValue(vehicleRangeAtom);
  const distance = useAtomValue(distanceAtom);

  return (
    <>
      <Head>
        <title>Onnatank</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center bg-white">
        <div className="justify-top container flex flex-col items-center gap-12 py-32 px-4 ">
          <h1 className="text-5xl font-light tracking-tight text-black sm:text-[5rem]">
            Onnatank
          </h1>
        </div>

        <VehicleSelection />

        <GeoLocation />

        <Map />

        <p>{JSON.stringify(vehicle, null, 2)}</p>
        <p>Range: {range}</p>
        <p>Distance: {distance}</p>
      </main>
    </>
  );
};

export default Home;
